#!/usr/bin/lua


local fd = io.open(arg[1])
local addr = 0x10000000
local done = false

print ""
print "echo 0"

while true do
	local cmd = string.format("mem w %08x ", addr)

	c = fd:read(16)
	if not c then
		break
	end

	c = c .. "                           "

	local sum = 0
	for i = 1, 16 do
		sum = (sum + string.byte(c, i)) % 256
	end
	cmd = cmd .. string.format("%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x", 
		sum, string.byte(c, 1, #c))
	print(cmd)
	addr = addr + 16

end

print "hop"
print "echo 1"

-- vi: ft=lua ts=3 sw=3
