#!/usr/bin/lua


local fd = io.open(arg[1])
local addr = 0
local done = false
local sum1 = 0

print ""
print "echo 0"

while true do
	local cmd = string.format("fl w %06x ", addr)

	c = fd:read(16)
	if not c then
		break
	end

	c = c .. "                           "

	sum1 = 0
	for i = 1, 16 do
		local c = string.byte(c, i)
		sum1 = (sum1 + c) % 256
	end
	cmd = cmd .. string.format("%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x", 
		sum1, string.byte(c, 1, #c))
	print(cmd)
	addr = addr + 16

	for i = 1, 3000000 do end

end

print "echo 1"


-- vi: ft=lua ts=3 sw=3
