#!/usr/bin/lua

local name = arg[1]
local fname = "modules/" .. name .. "/" .. name .. ".bin"

local fd = io.open(fname)
local addr = 0x10000000
local done = false

print ""
print "echo 0"
print "m4 s"
os.execute("sleep 0.3")
print "m4 h"

while true do
	local cmd = string.format("mem w %08x ", addr)

	c = fd:read(16)
	if not c then
		break
	end

	c = c .. "                           "

	local sum = 0
	for i = 1, 16 do
		sum = (sum + string.byte(c, i)) % 256
	end
	cmd = cmd .. string.format("%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x", 
		sum, string.byte(c, 1, #c))
	print(cmd)
	addr = addr + 16

end

print "m4 g"
print "echo 1"

-- vi: ft=lua ts=3 sw=3
