#!/usr/bin/lua


local fd = io.open(arg[1])
local addr = tonumber(arg[2]) or 0
local done = false
local sum1 = 0
local bufaddr = 0
local page_size = 528

print ""
print "echo 0"


while true do
	local cmd = string.format("fl l %x ", bufaddr)

	c = fd:read(16)

	if not c or bufaddr == page_size then
		print(string.format("f W %x", addr))
		addr = addr + page_size
		bufaddr = 0
	end

	if not c then
		break
	end

	c = c .. "                           "

	sum1 = 0
	for i = 1, 16 do
		local c = string.byte(c, i)
		sum1 = (sum1 + c) % 256
	end
	cmd = cmd .. string.format("%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x", 
		sum1, string.byte(c, 1, #c))

	print(cmd)
	bufaddr = bufaddr + 16


end

print "echo 1"


-- vi: ft=lua ts=3 sw=3
